export const events = [
  {
    title: "Google I/O 2026",
    image: "/images/event1.png",
    slug: "google-io-2026",
    location: "Mountain View, CA, USA",
    date: "May 20, 2026",
    time: "10:00 AM PDT",
  },
  {
    title: "Microsoft Build 2026",
    image: "/images/event2.png",
    slug: "microsoft-build-2026",
    location: "Seattle, WA, USA",
    date: "May 19, 2026",
    time: "9:00 AM PDT",
  },
  {
    title: "WeAreDevelopers World Congress 2026",
    image: "/images/event3.png",
    slug: "wearedevelopers-world-congress-2026",
    location: "Berlin, Germany",
    date: "July 8, 2026",
    time: "9:30 AM CEST",
  },
  {
    title: "TechCrunch Disrupt 2026",
    image: "/images/event4.png",
    slug: "techcrunch-disrupt-2026",
    location: "San Francisco, CA, USA",
    date: "October 27, 2026",
    time: "8:30 AM PDT",
  },
  {
    title: "ETHGlobal Hackathon - New York 2026",
    image: "/images/event5.png",
    slug: "ethglobal-new-york-2026",
    location: "New York, NY, USA",
    date: "September 18, 2026",
    time: "6:00 PM EDT",
  },
  {
    title: "React Advanced Meetup: State of React 2026",
    image: "/images/event6.png",
    slug: "react-advanced-meetup-2026",
    location: "London, UK",
    date: "June 11, 2026",
    time: "6:30 PM BST",
  },
  {
    title: "PyCon US 2026",
    image: "/images/event-full.png",
    slug: "pycon-us-2026",
    location: "Pittsburgh, PA, USA",
    date: "April 15, 2026",
    time: "9:00 AM EDT",
  },
];
